name: Release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: lget-linux-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: lget-macos-aarch64
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
          save-if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename Artifact
        run: mv target/${{ matrix.target }}/release/lget${{ runner.os == 'Windows' && '.exe' || '' }} target/${{ matrix.target }}/release/${{ matrix.name }}

      - name: Upload Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.name }}
          asset_name: ${{ matrix.name }}
          tag: ${{ github.ref }}

  publish-aur:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: Prepare PKGBUILD
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          sed -i "s/^pkgver=.*/pkgver=$VERSION/" packaging/aur-bin/PKGBUILD
          sed -i "s/^pkgrel=.*/pkgrel=1/" packaging/aur-bin/PKGBUILD
          sleep 3

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v3
        with:
          pkgname: lget-bin
          pkgbuild: packaging/aur-bin/PKGBUILD
          updpkgsums: true
          commit_username: "pencelheimer"
          commit_email: "pencelheimer@proton.me"
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "${GITHUB_REF_NAME}"
          ssh_keyscan_types: ed25519

      - name: Update Submodule Pointer in Main Repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git submodule update --remote packaging/aur-bin

          git add packaging/aur-bin
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore(aur-bin): sync submodule to ${GITHUB_REF_NAME}"
            git push origin HEAD:main
          fi
